src/java/com/supinfo/suptracking/entity/Car.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supinfo.suptracking.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import org.hibernate.validator.constraints.NotEmpty;

/**
 *
 * @author Pascal
 */
@Entity
public class Car implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    @NotEmpty(message="You must enter a name for your car")
    private String name;
    
    @NotEmpty(message="You must enter the brand of your car")
    private String brand;
    
    @NotNull(message="You must enter the year of first entry into service of your car")
    private int entryYear;
    
    @NotNull
    private double latitude;
    
    @NotNull
    private double longitude;

    @NotNull
    private Timestamp updateTimestamp;
    
    @NotNull
    @ManyToOne
    @JoinColumn(name="user_fk")
    private User user;
    
    @OneToMany(cascade=CascadeType.ALL, mappedBy="car")
    private List<Zone> zones;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public int getEntryYear() {
        return entryYear;
    }

    public void setEntryYear(int entryYear) {
        this.entryYear = entryYear;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Timestamp getUpdateTimestamp() {
        return updateTimestamp;
    }

    public void setUpdateTimestamp(Timestamp updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Zone> getZones() {
        return zones;
    }

    public void setZones(List<Zone> zones) {
        this.zones = zones;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Car)) {
            return false;
        }
        Car other = (Car) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.supinfo.suptracking.entity.Car[ id=" + id + " ]";
    }
    
}

src/java/com/supinfo/suptracking/controller/CarController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.supinfo.suptracking.controller;

import com.supinfo.suptracking.entity.Car;
import com.supinfo.suptracking.entity.User;
import com.supinfo.suptracking.service.CarService;
import java.sql.Timestamp;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;

/**
 *
 * @author Pascal
 */
@ManagedBean
@RequestScoped
public class CarController {

    @EJB
    CarService carService;
    
    User user = (User) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("user");
    
    private Car car = new Car();
    
    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }
    
    public String add(){
        car.setLatitude(10.10);
        car.setLongitude(12.12);
        car.setUpdateTimestamp(new Timestamp(System.currentTimeMillis()));
        car.setUser(user);
        carService.addCar(car);
        return "cars?faces-redirect=true";
    }
    
    public String edit(Long carId){
        Car oldcar = carService.findCarById(carId);
        oldcar.setName(car.getName());
        oldcar.setBrand(car.getBrand());
        oldcar.setEntryYear(car.getEntryYear());
        oldcar.setUpdateTimestamp(new Timestamp(System.currentTimeMillis()));
        carService.updateCar(oldcar);
        return "cars?faces-redirect=true";
    }
    public String delete(Long carId){
        carService.deleteCar(carId);
        return "cars?faces-redirect=true";
    }
    
    public DataModel<Car> getCarDatamodel() {
        List<Car> cars = carService.getCarByUser(user.getId());
        DataModel<Car> carDataModel = new ListDataModel<>(cars);
        return carDataModel;
    }
}

web/add_car.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Add car</title>
    </h:head>
    <h:body>
        <h:form>
            <h1><h:outputText value="Create car"/></h1>
            <h:panelGrid columns="2">
                <h:outputLabel value="Car name : " for="name" />
                <h:inputText id="name" value="#{carController.car.name}" title="CarName" />
                <h:outputLabel value="Brand : " for="brand" />
                <h:inputText id="brand" value="#{carController.car.brand}" title="Brand" />
                <h:outputLabel value="Entry year : " for="year" />
                <h:inputText id="year" value="#{carController.car.entryYear}" title="EntryYear" />
            </h:panelGrid>
            <h:commandButton action="#{carController.add}" value="Add car" />
        </h:form>
    </h:body>
</html>

web/add_zone.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <h1><h:outputText value="Add zone"/></h1>
            <h:panelGrid columns="2">
                <h:outputLabel value="Latitude : " for="latitude" />
                <h:inputText id="latitude" value="#{zoneController.zone.latitude}" title="Latitude" />
                <h:outputLabel value="Longitude : " for="longitude" />
                <h:inputText id="longitude" value="#{zoneController.zone.longitude}" title="Longitude" />
                <h:outputLabel value="Raduis : " for="radius" />
                <h:inputText id="radius" value="#{zoneController.zone.radius}" title="Radius" />
                <h:outputLabel value="Start Time : " for="start" />
                <h:inputText id="start" value="#{zoneController.zone.starttime}" title="StartTime" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                </h:inputText>
                <h:outputLabel value="End Time : " for="end" />
                <h:inputText id="end" value="#{zoneController.zone.endtime}" title="EndTime" >
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                </h:inputText>
            </h:panelGrid>
            <h:commandButton action="#{zoneController.add(param.id)}" value="Add zone" />
        </h:form>
    </h:body>
</html>

web/cars.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Your cars</title>
    </h:head>
    <h:body>
        <h:form>
            <h:commandLink action="#{userController.logout}" value="Log out" />
        </h:form>
        <h:dataTable value="#{carController.carDatamodel}" var="car">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Name"/>
                </f:facet>
                <h:outputText value="#{car.name}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Brand"/>
                </f:facet>
                <h:outputText value="#{car.brand}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Entry Year"/>
                </f:facet>
                <h:outputText value="#{car.entryYear}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="GPS Position"/>
                </f:facet>
                <h:outputText value="#{car.longitude};#{car.latitude}"/>
            </h:column>
            <h:column>
                <h:outputLink value="edit_car.xhtml">
                    <h:outputText value="Edit" />
                    <f:param value="#{car.id}" name="id"/>
                </h:outputLink>
            </h:column>
            <h:column>
                <h:form>
                    <h:commandLink action="#{carController.delete(car.id)}" value="Delete" />
                </h:form>
            </h:column>
        </h:dataTable>
        <h:outputLink value="add_car.xhtml">
            <h:outputText value="Add car" />
        </h:outputLink>
        Here is your created cars :
    </h:body>
</html>

web/edit_car.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <h1><h:outputText value="Edit car"/></h1>
            <h:panelGrid columns="2">
                <h:outputLabel value="Car name : " for="name" />
                <h:inputText id="name" value="#{carController.car.name}" title="CarName" />
                <h:outputLabel value="Brand : " for="brand" />
                <h:inputText id="brand" value="#{carController.car.brand}" title="Brand" />
                <h:outputLabel value="Entry year : " for="year" />
                <h:inputText id="year" value="#{carController.car.entryYear}" title="EntryYear" />
            </h:panelGrid>
            <h:commandButton action="#{carController.edit(param.id)}" value="Edit car" />
        </h:form>
        <h:dataTable value="#{zoneController.getZoneDatamodel(param.id)}" var="zone">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Zone Coordonnes"/>
                </f:facet>
                <h:outputText value="#{zone.latitude};#{zone.longitude}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Radius"/>
                </f:facet>
                <h:outputText value="#{zone.radius}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Start Time"/>
                </f:facet>
                <h:outputText value="#{zone.starttime}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="End Time"/>
                </f:facet>
                <h:outputText value="#{zone.endtime}"/>
            </h:column>
            <h:column>
                <h:form>
                    <h:commandLink action="#{zoneController.delete(zone.id)}" value="Delete" />
                </h:form>
            </h:column>
        </h:dataTable>
        <h:outputLink value="add_zone.xhtml">
            <h:outputText value="Add zone" />
            <f:param value="#{param.id}" name="id"/>
        </h:outputLink>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">



</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:outputLink value="register.xhtml">
            <h:outputText value="Register" />
        </h:outputLink>
        <h:form>
            <p>
                Username:
                <h:inputText id="username" value="#{userController.username}" />
                <br />
                Password:
                <h:inputSecret id="password" value="#{userController.password}" />
            <br />
            <h:commandButton action="#{userController.login}" value="Login" />
            </p>
        </h:form>
    </h:body>
</html>

web/offer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Offer page</title>
    <h:outputStylesheet library="css" name="main.css" />
</h:head>
<h:body>
    <h1>Premium offer</h1>
    
    <br />
	<p>10$/mouth for each car</p>
        <p>Real time GPS position \n 
           Full history of GPS positions \n 
           Possibility to manage each car</p>

		<br />
</h:body>
</html>

web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <h1><h:outputText value="Register"/></h1>
            <h:panelGrid columns="2">
                <h:outputLabel value="Username:" for="username" />
                <h:inputText id="username" value="#{userController.user.username}" title="Username" />
                <h:outputLabel value="Password:" for="password" />
                <h:inputSecret id="password" value="#{userController.user.password}" title="Password" />
                <h:outputLabel value="FirstName:" for="firstName" />
                <h:inputText id="firstName" value="#{userController.user.firstName}" title="FirstName" />
                <h:outputLabel value="LastName:" for="lastName" />
                <h:inputText id="lastName" value="#{userController.user.lastName}" title="LastName" />
                <h:outputLabel value="Email:" for="email" />
                <h:inputText id="email" value="#{userController.user.email}" title="Email" />
                <h:outputLabel value="Phone number:" for="number" />
                <h:inputText id="number" value="#{userController.user.number}" title="Number" />
                <h:outputLabel value="Card number:" for="card" />
                <h:inputText id="card" value="#{userController.user.card}" title="Card" />
            </h:panelGrid>
            <h:commandButton action="#{userController.register}" value="Register" />
        </h:form>
    </h:body>
</html>